### ISSUE TITLE
macOS All platforms - Super Mega XCFramework

### ISSUE THREAD

**Issue by danoli3** [openframeworks/apothecary#348]
An idea now with the XCFrameworks is to fix a further problem where we have multi platform libs being included without isolation to target, this problem is solved by XCFrameworks... however requires them all to be merged within.

Due to the complexities and computational limitations we require all the library runners to run separately for performance, isolation of problems for platform specific issues etc.

Merging all these binaries together can be done here on Apothecary via a concept known as _**workflow runners**_.

Example GitHub Action Workflow runner wait until types completed then run merge 

```
name: Merge Frameworks After Builds
on:
  workflow_run:
    workflows: ["iOS Build", "tvOS Build", "OSX Build", "WatchOS Build", "MacCatOS Build", "VisionOS-XROS Build"]
    types: [completed]
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        run: echo "This download will wait until all workflow runs by name above are completed. name is the trigger and must be exact"
      # Merge all targets into Super Mega XCFramework
       - name: Download Artifacts
        run: echo "Super Mega XCFramework"
```

This way we will have all platforms merged into one location: macOS

We can use the re-write to all platforms to distinguish osx/tvos/ios/catos/xros/watchos into libraries all targetting one specific location:
macos.

This solves many problems with one stone. All binaries are still isolated within the xcframework separately for each target platform.

Requirements: Artifacts of each post build deposited zip to the artifact cache system. 
Clean up of artifacts after merge. 

This process will not run if any listed names do not complete

For openFrameworks core this would require minimal adjustements inline with our switch out osx lib to macos, however now will be for all macOS platforms.

This would mean also a larger payload for release binaries for macOS as this would include all potential targets for the developer.
Probably best anyways as lets foster an environment for macOS developers to think they can and do whatever target they want within that architecture. Most oF developers I know always have iOS and macOS downloaded anyways.
