### ISSUE TITLE
Apple Distribution/Developer Signing Certs added to Apothecary (for XCFramework Signed)

### ISSUE THREAD

**Issue by danoli3** [openframeworks/apothecary#369]
Looks like we need Apple Developer / Distribution Signing  @ofTheo 

https://developer.apple.com/documentation/xcode/creating-a-multi-platform-binary-framework-bundle
<img width="822" alt="Screenshot 2024-03-22 at 2 56 26 pm" src="https://github.com/openframeworks/apothecary/assets/830748/b282772c-e7a3-4fa5-aea6-9bcb99c35f35">

This is only required for when using **Multiplatform Target** it seems however best to get this sorted now! 
- As this has more strict code signing requirements

Current PR xcframeworks no issues. Best we set this up though! Here's some guides

Changes can be made once added to Apothecary.
Refer to Project Generator - https://github.com/openframeworks/projectGenerator/tree/master/scripts

Or guide: https://localazy.com/blog/how-to-automatically-sign-macos-apps-using-github-actions

Then add to actions workflow when needed:
```
  env:
          GA_CI_SECRET: ${{ secrets.CI_SECRET }}
          CERTIFICATE_OSX_APPLICATION: ${{ secrets.CERTIFICATE_OSX_APPLICATION }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
          GA_APPLE_USERNAME: ${{ secrets.GA_APPLE_USERNAME }}
          GA_APPLE_PASS: ${{ secrets.GA_APPLE_PASS }}
          GA_NOTARIZE_PROVIDER: ${{ secrets.GA_NOTARIZE_PROVIDER }}
```

I would recommend making a new signing cert for Distribution and Developer so we can test both for these binaries.
Again this is just to validate to developers we built it here, its signed from here, and to our best ability is the most secure it can be :)
